<?php
/**
 * Created by PhpStorm.
 * User: Vince
 * Date: 22/02/2018
 * Time: 23:52
 */

namespace App\Tests\Services;


use App\Entity\Card;
use App\Services\Judger;
use Symfony\Bundle\FrameworkBundle\Tests\TestCase;

class JudgeTest extends TestCase
{
    /** @var Judger */
    private $judge;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->judge = new Judger();
    }

    public function testThatOnePairIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,1),
            new Card(2,3),
            new Card(3,5),
            new Card(2,7),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(1, $judge->getScore());
    }

    public function testThatTwoPairIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,1),
            new Card(2,3),
            new Card(3,3),
            new Card(2,7),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(2, $judge->getScore());
    }

    public function testThatThreeOfAKindIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,1),
            new Card(2,1),
            new Card(3,3),
            new Card(2,7),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(3, $judge->getScore());
    }

    public function testThatStraightIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,2),
            new Card(2,3),
            new Card(3,4),
            new Card(2,5),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(4, $judge->getScore());

        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,2),
            new Card(2,3),
            new Card(3,0),
            new Card(2,12),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(4, $judge->getScore());

        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,2),
            new Card(2,3),
            new Card(3,0),
            new Card(2,10),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertNotEquals(4, $judge->getScore());
    }

    public function testThatFlushIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(0,8),
            new Card(0,3),
            new Card(0,4),
            new Card(0,5),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(5, $judge->getScore());
    }

    public function testThatFullHouseIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,1),
            new Card(2,1),
            new Card(3,2),
            new Card(2,2),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(6, $judge->getScore());
    }

    public function testThatFourOfAKindIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(0,1),
            new Card(1,1),
            new Card(2,1),
            new Card(3,1),
            new Card(2,5),
            new Card(1,9),
            new Card(0,11)
        ]);

        $this->assertEquals(7, $judge->getScore());
    }

    public function testThatStraightFlushIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(1,1),
            new Card(1,2),
            new Card(1,3),
            new Card(1,4),
            new Card(1,5),
            new Card(2,9),
            new Card(0,11)
        ]);

        $this->assertEquals(8, $judge->getScore());
    }

    public function testThatRoyalFlushIsAsserted()
    {
        $judge = $this->judge->judge([
            new Card(Card::HEARTS,12),
            new Card(Card::HEARTS,11),
            new Card(Card::HEARTS,10),
            new Card(Card::HEARTS,9),
            new Card(Card::HEARTS,8),
            new Card(2,9),
            new Card(0,11)
        ]);

        $this->assertEquals(9, $judge->getScore());
    }

}